# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  host: localhost
  port: 3785
  secret_key_base: 4907471f72d98fe39e84d729035c4106227ac70dc02276acf7b42ecfbf308153523b8a7a4f9b93743fa830b774bed32ce569bd60d8399f1b32a0eff1bcfdd10d
  facebook_key: 1088631447858526
  facebook_secret: e8b1d45d600ad37077044ac47c58d211

test:
  host: localhost
  secret_key_base: 41726e25743d2c0890c966c6beac7eace8a20ed541e8abb6d3db8832f3c05b506989085c6ed4f3ccebd9e1abe10d2ba6c7328e53c97d1c31b583be7b01f59fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  host: noggalito.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <% ENV["FACEBOOK_KEY"] %>
  facebook_secret: <% ENV["FACEBOOK_SECRET"] %>
